---
name: ci
on:
  pull_request:
  push:
    branches:
      - "release/**"
jobs:
  yamllint:
    uses: Ex4amp1e/.github/.github/workflows/yamllint.yaml@main

  build-and-test:
    uses: Ex4amp1e/.github/.github/workflows/build-and-test.yaml@main
    with:
      os: '["ubuntu-latest", "macos-latest", "windows-latest"]'

  golangci-lint:
    uses: Ex4amp1e/.github/.github/workflows/golangci-lint.yaml@main
    with:
      linter-version: v1.60.3

  exclude-fmt-errorf:
    uses: Ex4amp1e/.github/.github/workflows/exclude-fmt-errorf.yaml@main

  restrict-nsm-deps:
    uses: Ex4amp1e/.github/.github/workflows/restrict-nsm-deps.yaml@main
    with:
      allowed_repositories: "api"

  checkgomod:
    uses: Ex4amp1e/.github/.github/workflows/checkgomod.yaml@main

  gogenerate:
    uses: Ex4amp1e/.github/.github/workflows/sdk-gogenerate.yaml@main

  exclude-replace:
    uses: Ex4amp1e/.github/.github/workflows/exclude-replace.yaml@main

  code-cov:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.5
      - run: |
          go test -coverprofile=coverage-${{ matrix.os }}.txt -covermode=atomic -race ./...
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
